version: '3.6'

services:
  db:
    image: "${arch}mariadb:10.5"
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - nextcloud.env

  redis:
    image: "${arch}redis:alpine"
    volumes:
      - redis:/data
    restart: always

  cloud:
    image: "${arch}nextcloud:fpm-alpine"
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
    env_file:
      - nextcloud.env
    depends_on:
      - db
      - redis

  nginx:
    image: "${arch}nginx:alpine"
    restart: always
    ports:
      - 443:443/tcp
    volumes:
      - nextcloud:/var/www/html:ro
      - logs:/var/log/nginx

      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./nginx/headers.conf:/etc/nginx/headers.conf
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx/ssl/:/etc/nginx/ssl/

      - ./nextcloud.conf:/etc/nginx/conf.d/https.conf
    depends_on:
      - cloud

  cron:
    image: "${arch}nextcloud:fpm-alpine"
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  logs:
  redis:
