version: '3.9'

networks:
  proxy:
    external: true

services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - nextcloud.env
    networks:
      - proxy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "nextcloud" ]
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 60s

  redis:
    image: redis:7-alpine
    volumes:
      - redis:/data
    restart: always
    networks:
      - proxy
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 3s
      timeout: 5s
      retries: 10

  cloud:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - ./php.ini:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
    env_file:
      - nextcloud.env
    depends_on:
      - db
      - redis
    networks:
      - proxy

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
      - logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.localhost`)
      - traefik.http.services.nextcloud.loadbalancer.server.port=80

      - traefik.http.middlewares.nextredirect.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.nextredirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.nextcloud.middlewares=nextredirect
      - traefik.http.middlewares.nc-header.headers.frameDeny=true
      - traefik.http.middlewares.nc-header.headers.contentTypeNosniff=true
      - traefik.http.middlewares.nc-header.headers.stsIncludeSubdomains=true
      - traefik.http.middlewares.nc-header.headers.stsPreload=true
      - traefik.http.middlewares.nc-header.headers.stsSeconds=31536000
      - traefik.http.middlewares.nc-header.headers.referrerPolicy=same-origin
      - traefik.http.middlewares.nc-header.headers.browserXssFilter=true
      - traefik.http.middlewares.nc-header.headers.customRequestHeaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.nc-header.headers.customResponseHeaders.X-Robots-Tag=none
      - traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN

    networks:
      - proxy

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
      - cloud

volumes:
  db:
  nextcloud:
  logs:
  redis:
