version: '3.8'

networks:
  web:
    external:
      name: traefik-net
  nextcloud:
    external: false

services:
  db:
    image: "${arch}postgres:13-alpine"
    security_opt:
      - seccomp:unconfined
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - nextcloud.env
    networks:
      - nextcloud

  redis:
    image: "${arch}redis:6.0-alpine"
    volumes:
      - redis:/data
    restart: always
    networks:
      - nextcloud

  cloud:
    image: "${arch}nextcloud:fpm-alpine"
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - ./php.ini:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
    env_file:
      - nextcloud.env
    depends_on:
      - db
      - redis
    networks:
      - nextcloud

  nginx:
    image: "${arch}nginx:alpine"
    restart: always
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html:ro
      - logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`test.local`)
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.tls.certresolver=myresolver
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.docker.network=traefik-net
    networks:
      - nextcloud
      - web

  cron:
    image: "${arch}nextcloud:fpm-alpine"
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
      - cloud
    networks:
      - nextcloud

volumes:
  db:
  nextcloud:
  logs:
  redis:
