version: '3.8'

networks:
  web:
    external:
      name: traefik-net
  nextcloud:
    external: false

services:
  db:
    image: postgres:14-alpine
    platform: "${arch}"
    security_opt:
      - seccomp:unconfined
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - nextcloud.env
    networks:
      - nextcloud
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "nextcloud", "-d", "nextcloud" ]
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 60s

  redis:
    image: redis:7-alpine
    platform: "${arch}"
    volumes:
      - redis:/data
    restart: always
    networks:
      - nextcloud
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 3s
      timeout: 5s
      retries: 10

  cloud:
    image: nextcloud:fpm-alpine
    platform: "${arch}"
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - ./php.ini:/usr/local/etc/php-fpm.d/www.conf:ro
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
    env_file:
      - nextcloud.env
    depends_on:
      - db
      - redis
    networks:
      - nextcloud

  nginx:
    image: nginx:alpine
    platform: "${arch}"
    restart: always
    ports:
      - 80:80
    volumes:
      - nextcloud:/var/www/html:ro
      - logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - cloud
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.entrypoints=websecure
      - traefik.http.routers.nginx.tls.certresolver=myresolver
      - traefik.http.services.nginx.loadbalancer.server.port=80
      - traefik.docker.network=traefik-net
    networks:
      - nextcloud
      - web

  cron:
    image: nextcloud:fpm-alpine
    platform: "${arch}"
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
      - cloud
    networks:
      - nextcloud

volumes:
  db:
  nextcloud:
  logs:
  redis:
